# go-svc-bootstrap Global Configuration

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[go-svc-bootstrap]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  https: false
  addr: 8888
  db-type: 'mysql'
  oss-type: 'local'
  use-multipoint: false